/** THIS FILE IS AUTOGENERATED. REGENERATE THROUGH npm run generate:constants:icons */

import { Seasons } from './enums/Seasons';
import type { ReadonlyDeep } from 'type-fest';

/** Season icons */
import Spring from '../assets/seasons/Spring.png';
import Summer from '../assets/seasons/Summer.png';
import Fall from '../assets/seasons/Fall.png';
import Winter from '../assets/seasons/Winter.png';

/** Seed icons */
import Catmint_seed from '../assets/seeds/Catmint_seed.webp';
import Corn_seed from '../assets/seeds/Corn_seed.webp';
import Temple_flower_seed from '../assets/seeds/Temple_flower_seed.webp';

/** Crop icons */
import Catmint from '../assets/crops/Catmint.webp';
import Corn from '../assets/crops/Corn.webp';
import Temple_flower from '../assets/crops/Temple_flower.webp';

export const ICONS_BY_SEASON = {
  [Seasons.Spring]: Spring,
  [Seasons.Summer]: Summer,
  [Seasons.Fall]: Fall,
  [Seasons.Winter]: Winter,
} as const;

export const CROP_ICONS_BY_CROP_ID: ReadonlyDeep<Record<string, string>> = {
  Catmint,
  Corn,
  'Temple flower': Temple_flower,
} as const;

export const SEED_ICONS_BY_CROP_ID: ReadonlyDeep<Record<string, string>> = {
  Catmint: Catmint_seed,
  Corn: Corn_seed,
  'Temple flower': Temple_flower_seed,
} as const;
