/** THIS FILE IS AUTOGENERATED. REGENERATE THROUGH npm run generate:constants:icons */

import { Seasons } from './enums/Seasons';
import type { ReadonlyDeep } from 'type-fest';

/** Season icons */
import Spring from '../assets/seasons/Spring.png';
import Summer from '../assets/seasons/Summer.png';
import Fall from '../assets/seasons/Fall.png';
import Winter from '../assets/seasons/Winter.png';

/** Seed icons */
import Corn_seed from '../assets/seeds/Corn_seed.png';

/** Crop icons */
import Corn from '../assets/crops/Corn.png';

export const ICONS_BY_SEASON = {
  [Seasons.Spring]: Spring,
  [Seasons.Summer]: Summer,
  [Seasons.Fall]: Fall,
  [Seasons.Winter]: Winter,
} as const;

export const CROP_ICONS_BY_CROP_ID: ReadonlyDeep<Record<string, string>> = {
  Corn,
} as const;

export const SEED_ICONS_BY_CROP_ID: ReadonlyDeep<Record<string, string>> = {
  Corn: Corn_seed,
} as const;
