import keyBy from 'lodash/keyBy';
import type { Crop } from '../../types/Crop';
import type { ReadonlyDeep } from 'type-fest';
import { Seasons, type Season } from '../enums/Seasons';

export type CropsBySeason = { [season in Season]: ReadonlyDeep<Crop>[] };

export const CROPS: ReadonlyDeep<Crop[]> = [
  /** Spring */
  {
    id: 'Cabbage',
    name: 'Cabbage',
    seasons: [Seasons.Spring],
    buyPrices: [70],
    daysToGrow: 9,
    sellPrice: 180,
    recipeIds: [],
  },
  {
    id: 'Carrot',
    name: 'Carrot',
    seasons: [Seasons.Spring],
    buyPrices: [40],
    daysToGrow: 6,
    sellPrice: 80,
    recipeIds: [],
  },
  {
    id: 'Chickpea',
    name: 'Chickpea',
    seasons: [Seasons.Spring],
    buyPrices: [],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Daffodil',
    name: 'Daffodil',
    seasons: [Seasons.Spring],
    buyPrices: [15],
    daysToGrow: 4,
    sellPrice: 25,
    recipeIds: [],
  },
  {
    id: 'Lilac',
    name: 'Lilac',
    seasons: [Seasons.Spring],
    buyPrices: [],
    daysToGrow: 9,
    daysToRegrow: 3,
    sellPrice: 35,
    recipeIds: [],
  },
  {
    id: 'Peas',
    name: 'Peas',
    seasons: [Seasons.Spring],
    buyPrices: [300],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 135,
    recipeIds: [],
  },
  {
    id: 'Potato',
    name: 'Potato',
    seasons: [Seasons.Spring],
    buyPrices: [40],
    daysToGrow: 6,
    sellPrice: 75,
    recipeIds: [],
  },
  {
    id: 'Snowdrop anemone',
    name: 'Snowdrop Anemone',
    seasons: [Seasons.Spring],
    buyPrices: [],
    daysToGrow: 6,
    sellPrice: 40,
    recipeIds: [],
  },
  {
    id: 'Strawberry',
    name: 'Strawberry',
    seasons: [Seasons.Spring],
    buyPrices: [300],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 125,
    recipeIds: [],
  },
  {
    id: 'Tulip',
    name: 'Tulip',
    seasons: [Seasons.Spring],
    buyPrices: [20],
    daysToGrow: 6,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Turnip',
    name: 'Turnip',
    seasons: [Seasons.Spring],
    buyPrices: [25],
    daysToGrow: 4,
    sellPrice: 40,
    recipeIds: [],
  },

  /** Summer */
  {
    id: 'Basil',
    name: 'Basil',
    seasons: [Seasons.Summer],
    buyPrices: [],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Catmint',
    name: 'Catmint',
    seasons: [Seasons.Summer],
    buyPrices: [20],
    daysToGrow: 6,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Chili pepper',
    name: 'Chili Pepper',
    seasons: [Seasons.Summer],
    buyPrices: [40],
    daysToGrow: 6,
    sellPrice: 75,
    recipeIds: [],
  },
  {
    id: 'Corn',
    name: 'Corn',
    seasons: [Seasons.Summer],
    buyPrices: [300],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 125,
    recipeIds: ['Grilled corn', 'Summer salad', 'Faux corn', 'Corn sign'],
  },
  {
    id: 'Cosmos',
    name: 'Cosmos',
    seasons: [Seasons.Summer],
    buyPrices: [20],
    daysToGrow: 6,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Cucumber',
    name: 'Cucumber',
    seasons: [Seasons.Summer],
    buyPrices: [25],
    daysToGrow: 4,
    sellPrice: 40,
    recipeIds: [],
  },
  {
    id: 'Daisy',
    name: 'Daisy',
    seasons: [Seasons.Summer],
    buyPrices: [10],
    daysToGrow: 4,
    sellPrice: 15,
    recipeIds: [],
  },
  {
    id: 'Dill',
    name: 'Dill',
    seasons: [Seasons.Summer],
    buyPrices: [],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Iris',
    name: 'Iris',
    seasons: [Seasons.Summer],
    buyPrices: [],
    daysToGrow: 6,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Marigold',
    name: 'Marigold',
    seasons: [Seasons.Summer],
    buyPrices: [],
    daysToGrow: 9,
    sellPrice: 40,
    recipeIds: [],
  },
  {
    id: 'Night queen',
    name: 'Night Queen',
    seasons: [Seasons.Summer],
    buyPrices: [],
    daysToGrow: 6,
    sellPrice: 40,
    recipeIds: [],
  },
  {
    id: 'Oregano',
    name: 'Oregano',
    seasons: [Seasons.Summer],
    buyPrices: [],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Sage',
    name: 'Sage',
    seasons: [Seasons.Summer],
    buyPrices: [],
    daysToGrow: 6,
    daysToRegrow: 3,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Sugar cane',
    name: 'Sugar Cane',
    seasons: [Seasons.Summer],
    buyPrices: [40],
    daysToGrow: 6,
    sellPrice: 80,
    recipeIds: [],
  },
  {
    id: 'Sunflower',
    name: 'Sunflower',
    seasons: [Seasons.Summer],
    buyPrices: [20],
    daysToGrow: 6,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Tea',
    name: 'Tea',
    seasons: [Seasons.Summer],
    buyPrices: [300],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 135,
    recipeIds: [],
  },
  {
    id: 'Thyme',
    name: 'Thyme',
    seasons: [Seasons.Summer],
    buyPrices: [],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Tomato',
    name: 'Tomato',
    seasons: [Seasons.Summer],
    buyPrices: [300],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 125,
    recipeIds: [],
  },
  {
    id: 'Watermelon',
    name: 'Watermelon',
    seasons: [Seasons.Summer],
    buyPrices: [70],
    daysToGrow: 9,
    sellPrice: 180,
    recipeIds: [],
  },

  /** Fall */
  {
    id: 'Broccoli',
    name: 'Broccoli',
    seasons: [Seasons.Fall],
    buyPrices: [40],
    daysToGrow: 6,
    sellPrice: 75,
    recipeIds: [],
  },
  {
    id: 'Celosia',
    name: 'Celosia',
    seasons: [Seasons.Fall],
    buyPrices: [15],
    daysToGrow: 4,
    sellPrice: 25,
    recipeIds: [],
  },
  {
    id: 'Chrysanthemum',
    name: 'Chrysanthemum',
    seasons: [Seasons.Fall],
    buyPrices: [20],
    daysToGrow: 6,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Cranberry',
    name: 'Cranberry',
    seasons: [Seasons.Fall],
    buyPrices: [300],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 125,
    recipeIds: [],
  },
  {
    id: 'Garlic',
    name: 'Garlic',
    seasons: [Seasons.Fall],
    buyPrices: [],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Heather',
    name: 'Heather',
    seasons: [Seasons.Fall],
    buyPrices: [],
    daysToGrow: 9,
    daysToRegrow: 3,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Moon fruit',
    name: 'Moon Fruit',
    seasons: [Seasons.Fall],
    buyPrices: [],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 35,
    recipeIds: [],
  },
  {
    id: 'Onion',
    name: 'Onion',
    seasons: [Seasons.Fall],
    buyPrices: [300],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 135,
    recipeIds: [],
  },
  {
    id: 'Pumpkin',
    name: 'Pumpkin',
    seasons: [Seasons.Fall],
    buyPrices: [70],
    daysToGrow: 9,
    sellPrice: 180,
    recipeIds: [],
  },
  {
    id: 'Rice stalk',
    name: 'Rice Stalk',
    seasons: [Seasons.Fall],
    buyPrices: [300],
    daysToGrow: 9,
    daysToRegrow: 3,
    sellPrice: 150,
    recipeIds: [],
  },
  {
    id: 'Rosemary',
    name: 'Rosemary',
    seasons: [Seasons.Fall],
    buyPrices: [],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Sweet potato',
    name: 'Sweet Potato',
    seasons: [Seasons.Fall],
    buyPrices: [25],
    daysToGrow: 4,
    sellPrice: 40,
    recipeIds: [],
  },
  {
    id: 'Viola',
    name: 'Viola',
    seasons: [Seasons.Fall],
    buyPrices: [],
    daysToGrow: 6,
    sellPrice: 40,
    recipeIds: [],
  },
  {
    id: 'Wheat',
    name: 'Wheat',
    seasons: [Seasons.Fall],
    buyPrices: [300],
    daysToGrow: 9,
    daysToRegrow: 3,
    sellPrice: 150,
    recipeIds: [],
  },

  /** Winter */
  {
    id: 'Beet',
    name: 'Beet',
    seasons: [Seasons.Winter],
    buyPrices: [25],
    daysToGrow: 4,
    sellPrice: 40,
    recipeIds: [],
  },
  {
    id: 'Burdock root',
    name: 'Burdock Root',
    seasons: [Seasons.Winter],
    buyPrices: [],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Cauliflower',
    name: 'Cauliflower',
    seasons: [Seasons.Winter],
    buyPrices: [40],
    daysToGrow: 6,
    sellPrice: 75,
    recipeIds: [],
  },
  {
    id: 'Daikon radish',
    name: 'Daikon Radish',
    seasons: [Seasons.Winter],
    buyPrices: [70],
    daysToGrow: 9,
    sellPrice: 180,
    recipeIds: [],
  },
  {
    id: 'Frost lily',
    name: 'Frost Lily',
    seasons: [Seasons.Winter],
    buyPrices: [15],
    daysToGrow: 4,
    sellPrice: 25,
    recipeIds: [],
  },
  {
    id: 'Jasmine',
    name: 'Jasmine',
    seasons: [Seasons.Winter],
    buyPrices: [],
    daysToGrow: 9,
    daysToRegrow: 3,
    sellPrice: 35,
    recipeIds: [],
  },
  {
    id: 'Poinsettia',
    name: 'Poinsettia',
    seasons: [Seasons.Winter],
    buyPrices: [20],
    daysToGrow: 6,
    sellPrice: 30,
    recipeIds: [],
  },
  {
    id: 'Snapdragon',
    name: 'Snapdragon',
    seasons: [Seasons.Winter],
    buyPrices: [],
    daysToGrow: 6,
    sellPrice: 40,
    recipeIds: [],
  },
  {
    id: 'Snow peas',
    name: 'Snow Peas',
    seasons: [Seasons.Winter],
    buyPrices: [300],
    daysToGrow: 5,
    daysToRegrow: 3,
    sellPrice: 125,
    recipeIds: [],
  },

  /** Multi-season */
  {
    id: 'Temple flower',
    name: 'Temple Flower',
    seasons: [Seasons.Spring, Seasons.Summer, Seasons.Fall, Seasons.Winter],
    sellPrice: 25,
    buyPrices: [],
    daysToGrow: 9,
    daysToRegrow: 3,
    recipeIds: [],
  },
];

export const CROPS_BY_ID = keyBy(CROPS, 'id');

export const CROPS_BY_SEASON: ReadonlyDeep<CropsBySeason> = CROPS.reduce(
  (cropsBySeason, crop) => {
    crop.seasons.forEach((season) => {
      cropsBySeason[season].push(crop);
    });
    return cropsBySeason;
  },
  Object.values(Seasons).reduce((cropsBySeason, season) => {
    cropsBySeason[season] = [];
    return cropsBySeason;
  }, {} as CropsBySeason),
);
